### ISSUE TITLE
NSListContentConfiguration issue

### ISSUE THREAD

**Issue by Mx-Iris** [flocked/AdvancedCollectionTableView#11] opened 2024-08-01 02:23 UTC
Dragging column cells on an OutlineView that uses NSListContentConfiguration shakes and the row height changes.

```swift
let cellView = outlineView.box.makeView(ofClass: NSTableCellView.self, owner: self)
var configuration = NSListContentConfiguration()
configuration.textProperties.font = .monospacedSystemFont(ofSize: 12, weight: .regular)
configuration.textProperties.lineBreakMode = .byTruncatingTail
configuration.margins = .init(top: 3, leading: 6, bottom: 3, trailing: 6)
switch tableColumnIdentifer {
   case .name:
       configuration.image = item.node.kind.ideIcon?.image
       configuration.text = item.node.name ?? "N/A"
   case .value:
       configuration.text = item.hasChildren ? "" : item.node.stringValue ?? ""
   case .index:
       configuration.text = item.isDisplayIndex ? item.siblingIndex.formatted() : ""
       configuration.textProperties.alignment = .center
}
cellView.contentConfiguration = configuration

return cellView
```

https://github.com/user-attachments/assets/6d46a385-e063-4d16-b783-7d0d736e8f43

**Comment by flocked** [comment] 2024-08-01 14:01
Is this an error that happens since a new commit?

**Comment by Mx-Iris** [comment] 2024-08-02 01:07
@flocked Yes. This is what happens after a certain commit

**Comment by flocked** [comment] 2024-08-02 09:30
Can you maybe please create a sample project? I can't reproduce the error.

**Comment by Mx-Iris** [comment] 2024-08-02 14:11
[AppKit-Xib.zip](https://github.com/user-attachments/files/16471426/AppKit-Xib.zip)
This is a directory file viewer example. There will be no shakes when the current columns can be fully displayed, but when the width of the outline view cannot accommodate all columns, dragging will cause shakes.

**Comment by flocked** [comment] 2024-08-02 18:39
Thanks. It's fixed in the last commit.

**Closed by flocked** 2024-08-02 18:39 UTC
